/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiLaundry;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mhmdf
 */
public class menu extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    DefaultTableModel tabModel;
    int xx, xy;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        koneksi DB = new koneksi();
        DB.dbconfig();
        con = DB.con;
        stat = DB.stm;
        
        batal();
        judulTablel();
        tampilData("");
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        idServeIncrement();
    }
        
    private void idServeIncrement() {
             try {
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  con=DriverManager.getConnection("jdbc:mysql://localhost/laundryCorvoo", "root", "");
                  String sql = "SELECT idServ FROM tblservices ORDER BY idServ DESC LIMIT 1";
                  PreparedStatement pre = con.prepareStatement(sql);
                  ResultSet rsl = pre.executeQuery();
                  if (rsl.next()) {
                     int id = rsl.getInt(1);
                     int n = id + 1;
                     idLayan.setText(Integer.toString(n));
                 }
                  idLayan.setEditable(false);
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
            }
    }
   private void batal() {
            inpNama.setText("");
            inpAlamat.setText("");
            inpTelp.setText("");
            comboLayanan.setSelectedItem("");
            inpHarga.setText("");
            inpBerat.setText("");
            totalH.setText("");
    }
    
    public void judulTablel() {
        Object[] judul = {
          "ID", "Nama", "Alamat", "No. Telepon", "Layanan", "Berat", "Total"  
        };
        tabModel = new DefaultTableModel(null, judul);
        tbDataLayanan.setModel(tabModel);
    }
    
    private void tampilData(String where) {
         try {
            stat = con.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = stat.executeQuery("SELECT * FROM tblservices" + where);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("idServ"),
                    rs.getString("nama"),
                    rs.getString("alamat"),
                    rs.getString("no_tlp"),
                    rs.getString("jenPelayanan"),
                    rs.getString("beratBaju"),
                    rs.getString("totalHarga"),
                };
                
                tabModel.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inpNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inpAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inpTelp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboLayanan = new javax.swing.JComboBox<>();
        inpBerat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalH = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        inpHarga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idLayan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataLayanan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(63, 162, 246));
        jPanel2.setPreferredSize(new java.awt.Dimension(1110, 200));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Perumahan Bukit Waringin Blok 12, Telepon. 0812900000, Website. www.jagonyacui.com");

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CORVOO LAUNDRY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 200));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(290, 520));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Nama");

        inpNama.setMargin(new java.awt.Insets(2, 10, 2, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Alamat");

        inpAlamat.setMargin(new java.awt.Insets(2, 10, 2, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Telepon");

        inpTelp.setMargin(new java.awt.Insets(2, 10, 2, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Pilih Layanan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Berat");

        comboLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Layanan", "Cuci-Setrika", "Cuci", "Setrika" }));
        comboLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLayananActionPerformed(evt);
            }
        });

        inpBerat.setMargin(new java.awt.Insets(2, 10, 2, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Total");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Kg");

        totalH.setBackground(new java.awt.Color(204, 204, 204));
        totalH.setMargin(new java.awt.Insets(2, 10, 2, 10));

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Harga");

        inpHarga.setMargin(new java.awt.Insets(2, 10, 2, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("ID Layanan");

        idLayan.setMargin(new java.awt.Insets(2, 10, 2, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inpAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inpNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inpTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(inpBerat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7))
                                .addComponent(totalH)
                                .addComponent(comboLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inpHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idLayan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(idLayan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inpNama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inpAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inpTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inpBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addGap(134, 134, 134))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, 700));

        tbDataLayanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDataLayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataLayananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDataLayanan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 720, 490));

        btnEdit.setText("UBAH");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCetak.setText("CETAK STRUK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                .addComponent(btnCetak)
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnCetak))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 760, 840, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         if (inpNama.getText().equals("") || inpAlamat.getText().equals("") || inpTelp.getText().equals("") || comboLayanan.getSelectedItem().equals("") || inpBerat.getText().equals("") || totalH.getText().equals(""))  {
        JOptionPane.showMessageDialog(null, "LENGKAPI DATA !!", "Laundry Corvoo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String namaCust = inpNama.getText();
            String alamatCust = inpAlamat.getText();
            String noTelp = inpTelp.getText();
            String jenisLayan = (String) comboLayanan.getSelectedItem();
            String hargaCuci = inpHarga.getText();
            String beratCucian = inpBerat.getText();
            String totalHarga = totalH.getText();

            try {
                stat = con.createStatement();
                String sql = "INSERT INTO tblservices (nama, alamat, no_tlp, jenPelayanan, hargaBarang, beratBaju, totalHarga) VALUES (?, ?, ?, ?, ?, ?, ?)";

                try (java.sql.PreparedStatement ta = con.prepareStatement(sql)) {
                    ta.setString(1, namaCust);
                    ta.setString(2, alamatCust);
                    ta.setString(3, noTelp);
                    ta.setString(4, jenisLayan);
                    ta.setString(5, hargaCuci);
                    ta.setString(6, beratCucian);
                    ta.setString(7, totalHarga);

                    ta.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan", "Laundry Corvoo", JOptionPane.INFORMATION_MESSAGE);
                // Reset form fields
                idServeIncrement();
                inpNama.setText("");
                inpAlamat.setText("");
                inpTelp.setText("");
                comboLayanan.setSelectedItem("");
                inpHarga.setText("");
                inpBerat.setText("");
                totalH.setText("");
                tampilData(""); 
            } catch (SQLException e) {
                System.out.println("ERROR");
                e.printStackTrace();
            }
          }  
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void comboLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLayananActionPerformed
         if (comboLayanan.getSelectedItem().equals("Cuci-Setrika")) {
                inpHarga.setText("8000");
        } else if (comboLayanan.getSelectedItem().equals("Cuci")) {
                inpHarga.setText("6000");
        } else if (comboLayanan.getSelectedItem().equals("Setrika")) {
                inpHarga.setText("2000");
        }
    }//GEN-LAST:event_comboLayananActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed

        try {
            if (inpNama.getText().equals("") || inpAlamat.getText().equals("") || inpTelp.getText().equals("") || comboLayanan.getSelectedItem().equals("") || inpBerat.getText().equals(""))  {
                JOptionPane.showMessageDialog(null, "LENGKAPI DATA !!", "Laundry Corvoo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int berat = Integer.parseInt(inpBerat.getText().toString());
                int hargaCuci = (int) Double.parseDouble(inpHarga.getText().toString());
                int jumlah = berat * hargaCuci;

                // Membuat cek jika hari ini jumat
                Calendar kalen = Calendar.getInstance();
                int perminggu = kalen.get(Calendar.DAY_OF_WEEK);

                // Definisikan diskon
                double disk = 0.0;
                String pemilihanDisk = comboLayanan.getSelectedItem().toString();
                if (perminggu == Calendar.FRIDAY) {
                    switch (pemilihanDisk) {
                        case "Cuci-Setrika":
                            disk = 0.08;
                            break;
                        case "Cuci":
                            disk = 0.05;
                            break;
                        case "Strika":
                            disk = 0.05;
                            break;
                    }
                }

                // mendapatkan diskon jika di hari jumat
                if (disk > 0.0) {
                    jumlah = jumlah - (int) (jumlah * disk);
                }

                totalH.setText(Integer.toString(jumlah));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void tbDataLayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataLayananMouseClicked
        idLayan.setText(tbDataLayanan.getValueAt(tbDataLayanan.getSelectedRow(), 0).toString());
        inpNama.setText(tbDataLayanan.getValueAt(tbDataLayanan.getSelectedRow(), 1).toString());
        inpAlamat.setText(tbDataLayanan.getValueAt(tbDataLayanan.getSelectedRow(), 2).toString());
        inpTelp.setText(tbDataLayanan.getValueAt(tbDataLayanan.getSelectedRow(), 3).toString());
        comboLayanan.setSelectedItem(tbDataLayanan.getValueAt(tbDataLayanan.getSelectedRow(), 4).toString());
        inpBerat.setText(tbDataLayanan.getValueAt(tbDataLayanan.getSelectedRow(), 5).toString());
        totalH.setText(tbDataLayanan.getValueAt(tbDataLayanan.getSelectedRow(), 6).toString());
        idLayan.setEditable(false);
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tbDataLayananMouseClicked


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (inpNama.getText().equals("") || inpAlamat.getText().equals("") || inpTelp.getText().equals("") || comboLayanan.getSelectedItem().equals("") || inpBerat.getText().equals("") || totalH.getText().equals(""))  {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !!", "Laundry Corvoo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                stat = con.createStatement();
                stat.executeUpdate("UPDATE tblservices SET " 
                        + "nama = '" + inpNama.getText() + "', "
                        + "alamat = '" + inpAlamat.getText() + "', "
                        + "no_tlp = '" + inpTelp.getText() + "', "
                        + "jenPelayanan = '" + comboLayanan.getSelectedItem() + "', "
                        + "hargaBarang = '" + inpHarga.getText() + "', "
                        + "beratBaju = '" + inpBerat.getText() + "', "
                        + "totalHarga = '" + totalH.getText() + "' "
                        + "WHERE idServ = '" + idLayan.getText() + "'");
                idServeIncrement();
                tampilData("");
                JOptionPane.showMessageDialog(null, "Data Barang Berhasil di Edit");
                batal();
                btnSimpan.setEnabled(true);
                btnEdit.setEnabled(true);
                btnHapus.setEnabled(true);
                btnBatal.setEnabled(true);
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                inpNama.setText("");
                inpAlamat.setText("");
                inpTelp.setText("");
                comboLayanan.setSelectedItem("");
                inpHarga.setText("");
                inpBerat.setText("");
                totalH.setText("");
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit ", "Laundry Corvoo", JOptionPane.INFORMATION_MESSAGE);
                tampilData("");
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    try {
            int jawab;
            
            if ((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin Menghapus Data ini?", "Confirm", JOptionPane.YES_NO_OPTION)) == 0) {
                stat = con.createStatement();
                stat.executeUpdate("DELETE FROM tblservices WHERE idServ='"
                    + tabModel.getValueAt(tbDataLayanan.getSelectedRow(), 0) + "'");
                tampilData("");
                batal();
                idServeIncrement();
                btnSimpan.setEnabled(true);
                btnHitung.setEnabled(true);
                btnEdit.setEnabled(true);
                btnHapus.setEnabled(true);
                }                                       
            } catch (SQLException e) {
              e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
             batal();
             idServeIncrement();
             btnSimpan.setEnabled(true);
             btnHitung.setEnabled(true);
             btnEdit.setEnabled(true);
             btnHapus.setEnabled(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
              java.sql.Connection con = null;
              try {
                  String driverSql = "com.mysql.cj.jdbc.Driver";
                  Class.forName(driverSql);
                  
                  con=DriverManager.getConnection("jdbc:mysql://localhost/laundryCorvoo", "root", "");
                  Statement stm = con.createStatement();
                  
                  try {
                      String report = ("C:\\Users\\Corvoo\\Documents\\"
                              + "NetBeansProjects\\Corvoo Laundry\\src\\" 
                              + "AplikasiLaundry\\cetakLayanan.jrxml");
                      HashMap hash = new HashMap();
                      // Mengambil Parameter dari ireport
                      hash.put("idserv", idLayan.getText());
                      JasperReport jr = JasperCompileManager.compileReport(report);
                      JasperPrint print = JasperFillManager.fillReport(jr, hash, con);
                      JasperViewer.viewReport(print, false);
                  } catch (Exception e) {
                        System.out.println("Laporan tidak bisa dilihat " + e.getMessage());
                  }
                  
            } catch (Exception e) {
                    System.out.println(e);
            }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//         try {
//            UIManager.setLookAndFeel( new FlatMacLightLaf() );
//            UIManager.put( "Button.arc", 5 );
//            UIManager.put( "Component.arc", 5 );
//            UIManager.put( "ProgressBar.arc", 5 );
//            UIManager.put( "TextComponent.arc", 5 );
//        } catch( Exception ex ) {
//            System.err.println( "Failed to initialize LaF" );
//        }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> comboLayanan;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField idLayan;
    private javax.swing.JTextField inpAlamat;
    private javax.swing.JTextField inpBerat;
    private javax.swing.JTextField inpHarga;
    private javax.swing.JTextField inpNama;
    private javax.swing.JTextField inpTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDataLayanan;
    private javax.swing.JTextField totalH;
    // End of variables declaration//GEN-END:variables




}
